services:
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U trainee -d url_shortener']
      interval: 6s
      retries: 5
    restart: always
    networks:
      - app-network
    volumes:
      - database_volume:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_PORT: ${APP_PORT}
      NODE_ENV: ${NODE_ENV}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}

    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - app-network

volumes:
  database_volume:

networks:
  app-network:
    driver: bridge
