services:
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U trainee -d url_shortener']
      interval: 6s
      retries: 5
    restart: always
    networks:
      - app-network
    volumes:
      - database_volume:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    container_name: redis-local
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 3
    restart: always

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_PORT: ${APP_PORT}
      NODE_ENV: ${NODE_ENV}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SALT_ROUND: ${SALT_ROUND}

    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - app-network
    volumes:
      - .:/usr/local/app
      - /usr/local/app/node_modules

volumes:
  database_volume:
  redis_data:

networks:
  app-network:
    driver: bridge
