services:
  postgresc:
    image: 'postgres'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U trainee -d url_shortener']
      interval: 6s
      retries: 5
    restart: always
    networks:
      - app-network
    volumes:
      - database_volume:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgresc:
        condition: service_healthy
    environment:
      HOST: ${DB_HOST}
      PORT: 5432
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      NAME: ${POSTGRES_DB}
    ports:
      - 3000:3000
    networks:
      - app-network

volumes:
  database_volume:

networks:
  app-network:
    driver: bridge
